--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-03-13 20:11:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 24935)
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    author character varying(255),
    description character varying(255),
    isbn character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    url character varying(255) NOT NULL
);


ALTER TABLE public.book OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 24944)
-- Name: book_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book_category (
    category_id bigint NOT NULL,
    book_id character varying(255) NOT NULL
);


ALTER TABLE public.book_category OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24949)
-- Name: book_reviews_ids; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book_reviews_ids (
    reviews_ids bigint,
    book_isbn character varying(255) NOT NULL
);


ALTER TABLE public.book_reviews_ids OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24953)
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.category OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 24952)
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4865 (class 0 OID 24935)
-- Dependencies: 217
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.book (author, description, isbn, title, url) FROM stdin;
\N	\N	isbn	title1	url1
\N	\N	isbn2	title2	url2
\N	\N	isbn3	title3	url3
\N	\N	isbn4	title4	url4
\.


--
-- TOC entry 4866 (class 0 OID 24944)
-- Dependencies: 218
-- Data for Name: book_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.book_category (category_id, book_id) FROM stdin;
1	isbn
1	isbn2
1	isbn3
1	isbn4
3	isbn4
\.


--
-- TOC entry 4867 (class 0 OID 24949)
-- Dependencies: 219
-- Data for Name: book_reviews_ids; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.book_reviews_ids (reviews_ids, book_isbn) FROM stdin;
\.


--
-- TOC entry 4869 (class 0 OID 24953)
-- Dependencies: 221
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.category (id, name) FROM stdin;
1	science
3	art
\.


--
-- TOC entry 4875 (class 0 OID 0)
-- Dependencies: 220
-- Name: category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_id_seq', 4, true);


--
-- TOC entry 4712 (class 2606 OID 24948)
-- Name: book_category book_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_category
    ADD CONSTRAINT book_category_pkey PRIMARY KEY (category_id, book_id);


--
-- TOC entry 4708 (class 2606 OID 24941)
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (isbn);


--
-- TOC entry 4710 (class 2606 OID 24943)
-- Name: book book_url_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_url_key UNIQUE (url);


--
-- TOC entry 4714 (class 2606 OID 24959)
-- Name: category category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_name_key UNIQUE (name);


--
-- TOC entry 4716 (class 2606 OID 24957)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- TOC entry 4717 (class 2606 OID 24960)
-- Name: book_category fkam8llderp40mvbbwceqpu6l2s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_category
    ADD CONSTRAINT fkam8llderp40mvbbwceqpu6l2s FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- TOC entry 4719 (class 2606 OID 24970)
-- Name: book_reviews_ids fkdaf05hf6k7g06uqv46k9bp9ef; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_reviews_ids
    ADD CONSTRAINT fkdaf05hf6k7g06uqv46k9bp9ef FOREIGN KEY (book_isbn) REFERENCES public.book(isbn);


--
-- TOC entry 4718 (class 2606 OID 24965)
-- Name: book_category fknyegcbpvce2mnmg26h0i856fd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_category
    ADD CONSTRAINT fknyegcbpvce2mnmg26h0i856fd FOREIGN KEY (book_id) REFERENCES public.book(isbn);


-- Completed on 2025-03-13 20:11:45

--
-- PostgreSQL database dump complete
--

