---------------------------------
-- Database configuration (H2)
---------------------------------

CREATE TABLE book (
    author VARCHAR(255),
    description VARCHAR(255),
    isbn VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    CONSTRAINT book_pkey PRIMARY KEY (isbn),
    CONSTRAINT book_url_key UNIQUE (url)
);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE book_category (
    category_id BIGINT NOT NULL,
    book_id VARCHAR(255) NOT NULL,
    CONSTRAINT book_category_pkey PRIMARY KEY (category_id, book_id),
    CONSTRAINT fk_book_category_category FOREIGN KEY (category_id) REFERENCES category(id),
    CONSTRAINT fk_book_category_book FOREIGN KEY (book_id) REFERENCES book(isbn)
);

CREATE TABLE book_reviews_ids (
    reviews_ids BIGINT,
    book_isbn VARCHAR(255) NOT NULL,
    CONSTRAINT fk_book_reviews FOREIGN KEY (book_isbn) REFERENCES book(isbn)
);
